// Start WF
console.log(modeloPageDetail.oData);

sap.m.MessageToast.show("Rejected!");

sap.ui.core.BusyIndicator.show(0);
sap.n.Planet9.function({
    id: "WorkflowInbox",
    method: "Reject",
    data: { id: modeloPageDetail.oData.id },
    success: function (data) {
        handleUpdate("Reject");
        sap.ui.core.BusyIndicator.hide();
    },
    error: function (data) {
        sap.ui.core.BusyIndicator.hide();

    }
});