if (typeof earliestOverdueDate === "undefined" || earliestOverdueDate === null || earliestOverdueDate === "") {
    return;
}

var today = new Date().getTime();
if (today < new Date(earliestOverdueDate).getTime()) {
    if (((new Date(earliestOverdueDate).getTime() - today) / (24 * 60 * 60 * 1000)) < 0.5) {
        return "Warning"
    } else {
        return "Success";
    }
} else {
    return "Error"
}