
var binding = oListWorkflow.getBinding("items");
var filter = new sap.ui.model.Filter({
    filters: [
        new sap.ui.model.Filter("title", "Contains", this.getValue()),
        new sap.ui.model.Filter("subTitle", "Contains", this.getValue()),
        new sap.ui.model.Filter("objectKey", "Contains", this.getValue()),
        new sap.ui.model.Filter("amount", "Contains", this.getValue()),
    ],
    and: false
})
binding.filter([filter]);