// Start WF
console.log(modeloPageDetail.oData);

sap.m.MessageToast.show("Approved!");

 sap.ui.core.BusyIndicator.show(0);
 sap.n.Planet9.function({
     id: "WorkflowInbox",
     method: "Approve",
     data: { id: modeloPageDetail.oData.id },
     success: function (data) {
        handleUpdate("Approve");
         sap.ui.core.BusyIndicator.hide();
     },
     error: function (data) {
         sap.ui.core.BusyIndicator.hide();

     }
 });